// Code generated by go-swagger; DO NOT EDIT.

package punch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostPunchInParams creates a new PostPunchInParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostPunchInParams() *PostPunchInParams {
	return &PostPunchInParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostPunchInParamsWithTimeout creates a new PostPunchInParams object
// with the ability to set a timeout on a request.
func NewPostPunchInParamsWithTimeout(timeout time.Duration) *PostPunchInParams {
	return &PostPunchInParams{
		timeout: timeout,
	}
}

// NewPostPunchInParamsWithContext creates a new PostPunchInParams object
// with the ability to set a context for a request.
func NewPostPunchInParamsWithContext(ctx context.Context) *PostPunchInParams {
	return &PostPunchInParams{
		Context: ctx,
	}
}

// NewPostPunchInParamsWithHTTPClient creates a new PostPunchInParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostPunchInParamsWithHTTPClient(client *http.Client) *PostPunchInParams {
	return &PostPunchInParams{
		HTTPClient: client,
	}
}

/* PostPunchInParams contains all the parameters to send to the API endpoint
   for the post punch in operation.

   Typically these are written to a http.Request.
*/
type PostPunchInParams struct {

	/* Email.

	   メールアドレス
	*/
	Email string

	/* Latitude.

	   緯度
	*/
	Latitude *string

	/* Longitude.

	   経度
	*/
	Longitude *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post punch in params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPunchInParams) WithDefaults() *PostPunchInParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post punch in params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPunchInParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post punch in params
func (o *PostPunchInParams) WithTimeout(timeout time.Duration) *PostPunchInParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post punch in params
func (o *PostPunchInParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post punch in params
func (o *PostPunchInParams) WithContext(ctx context.Context) *PostPunchInParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post punch in params
func (o *PostPunchInParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post punch in params
func (o *PostPunchInParams) WithHTTPClient(client *http.Client) *PostPunchInParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post punch in params
func (o *PostPunchInParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the post punch in params
func (o *PostPunchInParams) WithEmail(email string) *PostPunchInParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the post punch in params
func (o *PostPunchInParams) SetEmail(email string) {
	o.Email = email
}

// WithLatitude adds the latitude to the post punch in params
func (o *PostPunchInParams) WithLatitude(latitude *string) *PostPunchInParams {
	o.SetLatitude(latitude)
	return o
}

// SetLatitude adds the latitude to the post punch in params
func (o *PostPunchInParams) SetLatitude(latitude *string) {
	o.Latitude = latitude
}

// WithLongitude adds the longitude to the post punch in params
func (o *PostPunchInParams) WithLongitude(longitude *string) *PostPunchInParams {
	o.SetLongitude(longitude)
	return o
}

// SetLongitude adds the longitude to the post punch in params
func (o *PostPunchInParams) SetLongitude(longitude *string) {
	o.Longitude = longitude
}

// WriteToRequest writes these params to a swagger request
func (o *PostPunchInParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param email
	frEmail := o.Email
	fEmail := frEmail
	if fEmail != "" {
		if err := r.SetFormParam("email", fEmail); err != nil {
			return err
		}
	}

	if o.Latitude != nil {

		// form param latitude
		var frLatitude string
		if o.Latitude != nil {
			frLatitude = *o.Latitude
		}
		fLatitude := frLatitude
		if fLatitude != "" {
			if err := r.SetFormParam("latitude", fLatitude); err != nil {
				return err
			}
		}
	}

	if o.Longitude != nil {

		// form param longitude
		var frLongitude string
		if o.Longitude != nil {
			frLongitude = *o.Longitude
		}
		fLongitude := frLongitude
		if fLongitude != "" {
			if err := r.SetFormParam("longitude", fLongitude); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
