// Code generated by go-swagger; DO NOT EDIT.

package punch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kekecone/go-kincone/kinkone"
)

// PostPunchBreakReader is a Reader for the PostPunchBreak structure.
type PostPunchBreakReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPunchBreakReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostPunchBreakOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostPunchBreakUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostPunchBreakForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostPunchBreakUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostPunchBreakInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostPunchBreakOK creates a PostPunchBreakOK with default headers values
func NewPostPunchBreakOK() *PostPunchBreakOK {
	return &PostPunchBreakOK{}
}

/* PostPunchBreakOK describes a response with status code 200, with default header values.

正常時
*/
type PostPunchBreakOK struct {
	Payload *PostPunchBreakOKBody
}

func (o *PostPunchBreakOK) Error() string {
	return fmt.Sprintf("[POST /punch/break][%d] postPunchBreakOK  %+v", 200, o.Payload)
}
func (o *PostPunchBreakOK) GetPayload() *PostPunchBreakOKBody {
	return o.Payload
}

func (o *PostPunchBreakOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostPunchBreakOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPunchBreakUnauthorized creates a PostPunchBreakUnauthorized with default headers values
func NewPostPunchBreakUnauthorized() *PostPunchBreakUnauthorized {
	return &PostPunchBreakUnauthorized{}
}

/* PostPunchBreakUnauthorized describes a response with status code 401, with default header values.

APIトークンの値を確認して下さい。
*/
type PostPunchBreakUnauthorized struct {
	Payload *kinkone.ErrorModel
}

func (o *PostPunchBreakUnauthorized) Error() string {
	return fmt.Sprintf("[POST /punch/break][%d] postPunchBreakUnauthorized  %+v", 401, o.Payload)
}
func (o *PostPunchBreakUnauthorized) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *PostPunchBreakUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPunchBreakForbidden creates a PostPunchBreakForbidden with default headers values
func NewPostPunchBreakForbidden() *PostPunchBreakForbidden {
	return &PostPunchBreakForbidden{}
}

/* PostPunchBreakForbidden describes a response with status code 403, with default header values.

APIにアクセスする権限がありません。
*/
type PostPunchBreakForbidden struct {
	Payload *kinkone.ErrorModel
}

func (o *PostPunchBreakForbidden) Error() string {
	return fmt.Sprintf("[POST /punch/break][%d] postPunchBreakForbidden  %+v", 403, o.Payload)
}
func (o *PostPunchBreakForbidden) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *PostPunchBreakForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPunchBreakUnprocessableEntity creates a PostPunchBreakUnprocessableEntity with default headers values
func NewPostPunchBreakUnprocessableEntity() *PostPunchBreakUnprocessableEntity {
	return &PostPunchBreakUnprocessableEntity{}
}

/* PostPunchBreakUnprocessableEntity describes a response with status code 422, with default header values.

パラメータの値を確認して下さい。
*/
type PostPunchBreakUnprocessableEntity struct {
	Payload *kinkone.ErrorModel
}

func (o *PostPunchBreakUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /punch/break][%d] postPunchBreakUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *PostPunchBreakUnprocessableEntity) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *PostPunchBreakUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPunchBreakInternalServerError creates a PostPunchBreakInternalServerError with default headers values
func NewPostPunchBreakInternalServerError() *PostPunchBreakInternalServerError {
	return &PostPunchBreakInternalServerError{}
}

/* PostPunchBreakInternalServerError describes a response with status code 500, with default header values.

APIサーバーの内部的なエラーです。
*/
type PostPunchBreakInternalServerError struct {
	Payload *kinkone.ErrorModel
}

func (o *PostPunchBreakInternalServerError) Error() string {
	return fmt.Sprintf("[POST /punch/break][%d] postPunchBreakInternalServerError  %+v", 500, o.Payload)
}
func (o *PostPunchBreakInternalServerError) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *PostPunchBreakInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostPunchBreakOKBody post punch break o k body
swagger:model PostPunchBreakOKBody
*/
type PostPunchBreakOKBody struct {

	// response
	Response *PostPunchBreakOKBodyResponse `json:"response,omitempty"`

	// 結果コード
	ResultCode string `json:"result_code,omitempty"`

	// 結果ステータス
	Status bool `json:"status,omitempty"`
}

// Validate validates this post punch break o k body
func (o *PostPunchBreakOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResponse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostPunchBreakOKBody) validateResponse(formats strfmt.Registry) error {
	if swag.IsZero(o.Response) { // not required
		return nil
	}

	if o.Response != nil {
		if err := o.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postPunchBreakOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post punch break o k body based on the context it is used
func (o *PostPunchBreakOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostPunchBreakOKBody) contextValidateResponse(ctx context.Context, formats strfmt.Registry) error {

	if o.Response != nil {
		if err := o.Response.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postPunchBreakOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostPunchBreakOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostPunchBreakOKBody) UnmarshalBinary(b []byte) error {
	var res PostPunchBreakOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostPunchBreakOKBodyResponse APIレスポンス
swagger:model PostPunchBreakOKBodyResponse
*/
type PostPunchBreakOKBodyResponse struct {

	// attendance
	Attendance *kinkone.AttendanceModel `json:"attendance,omitempty"`
}

// Validate validates this post punch break o k body response
func (o *PostPunchBreakOKBodyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAttendance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostPunchBreakOKBodyResponse) validateAttendance(formats strfmt.Registry) error {
	if swag.IsZero(o.Attendance) { // not required
		return nil
	}

	if o.Attendance != nil {
		if err := o.Attendance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postPunchBreakOK" + "." + "response" + "." + "attendance")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post punch break o k body response based on the context it is used
func (o *PostPunchBreakOKBodyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAttendance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostPunchBreakOKBodyResponse) contextValidateAttendance(ctx context.Context, formats strfmt.Registry) error {

	if o.Attendance != nil {
		if err := o.Attendance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postPunchBreakOK" + "." + "response" + "." + "attendance")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostPunchBreakOKBodyResponse) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostPunchBreakOKBodyResponse) UnmarshalBinary(b []byte) error {
	var res PostPunchBreakOKBodyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
