// Code generated by go-swagger; DO NOT EDIT.

package flag_workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostFlagWorkflowWorkflowIDParams creates a new PostFlagWorkflowWorkflowIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostFlagWorkflowWorkflowIDParams() *PostFlagWorkflowWorkflowIDParams {
	return &PostFlagWorkflowWorkflowIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostFlagWorkflowWorkflowIDParamsWithTimeout creates a new PostFlagWorkflowWorkflowIDParams object
// with the ability to set a timeout on a request.
func NewPostFlagWorkflowWorkflowIDParamsWithTimeout(timeout time.Duration) *PostFlagWorkflowWorkflowIDParams {
	return &PostFlagWorkflowWorkflowIDParams{
		timeout: timeout,
	}
}

// NewPostFlagWorkflowWorkflowIDParamsWithContext creates a new PostFlagWorkflowWorkflowIDParams object
// with the ability to set a context for a request.
func NewPostFlagWorkflowWorkflowIDParamsWithContext(ctx context.Context) *PostFlagWorkflowWorkflowIDParams {
	return &PostFlagWorkflowWorkflowIDParams{
		Context: ctx,
	}
}

// NewPostFlagWorkflowWorkflowIDParamsWithHTTPClient creates a new PostFlagWorkflowWorkflowIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostFlagWorkflowWorkflowIDParamsWithHTTPClient(client *http.Client) *PostFlagWorkflowWorkflowIDParams {
	return &PostFlagWorkflowWorkflowIDParams{
		HTTPClient: client,
	}
}

/* PostFlagWorkflowWorkflowIDParams contains all the parameters to send to the API endpoint
   for the post flag workflow workflow ID operation.

   Typically these are written to a http.Request.
*/
type PostFlagWorkflowWorkflowIDParams struct {

	/* WorkflowID.

	   申請ID
	*/
	WorkflowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post flag workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFlagWorkflowWorkflowIDParams) WithDefaults() *PostFlagWorkflowWorkflowIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post flag workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFlagWorkflowWorkflowIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post flag workflow workflow ID params
func (o *PostFlagWorkflowWorkflowIDParams) WithTimeout(timeout time.Duration) *PostFlagWorkflowWorkflowIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post flag workflow workflow ID params
func (o *PostFlagWorkflowWorkflowIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post flag workflow workflow ID params
func (o *PostFlagWorkflowWorkflowIDParams) WithContext(ctx context.Context) *PostFlagWorkflowWorkflowIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post flag workflow workflow ID params
func (o *PostFlagWorkflowWorkflowIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post flag workflow workflow ID params
func (o *PostFlagWorkflowWorkflowIDParams) WithHTTPClient(client *http.Client) *PostFlagWorkflowWorkflowIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post flag workflow workflow ID params
func (o *PostFlagWorkflowWorkflowIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflowID adds the workflowID to the post flag workflow workflow ID params
func (o *PostFlagWorkflowWorkflowIDParams) WithWorkflowID(workflowID string) *PostFlagWorkflowWorkflowIDParams {
	o.SetWorkflowID(workflowID)
	return o
}

// SetWorkflowID adds the workflowId to the post flag workflow workflow ID params
func (o *PostFlagWorkflowWorkflowIDParams) SetWorkflowID(workflowID string) {
	o.WorkflowID = workflowID
}

// WriteToRequest writes these params to a swagger request
func (o *PostFlagWorkflowWorkflowIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workflowID
	if err := r.SetPathParam("workflowID", o.WorkflowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
