// Code generated by go-swagger; DO NOT EDIT.

package expense_workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kekecone/go-kincone/kinkone/model"
)

// DeleteExpenseWorkflowWorkflowIDReader is a Reader for the DeleteExpenseWorkflowWorkflowID structure.
type DeleteExpenseWorkflowWorkflowIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteExpenseWorkflowWorkflowIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteExpenseWorkflowWorkflowIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteExpenseWorkflowWorkflowIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteExpenseWorkflowWorkflowIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteExpenseWorkflowWorkflowIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteExpenseWorkflowWorkflowIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteExpenseWorkflowWorkflowIDOK creates a DeleteExpenseWorkflowWorkflowIDOK with default headers values
func NewDeleteExpenseWorkflowWorkflowIDOK() *DeleteExpenseWorkflowWorkflowIDOK {
	return &DeleteExpenseWorkflowWorkflowIDOK{}
}

/* DeleteExpenseWorkflowWorkflowIDOK describes a response with status code 200, with default header values.

正常時
*/
type DeleteExpenseWorkflowWorkflowIDOK struct {
	Payload *DeleteExpenseWorkflowWorkflowIDOKBody
}

func (o *DeleteExpenseWorkflowWorkflowIDOK) Error() string {
	return fmt.Sprintf("[DELETE /expense/workflow/{workflowID}][%d] deleteExpenseWorkflowWorkflowIdOK  %+v", 200, o.Payload)
}
func (o *DeleteExpenseWorkflowWorkflowIDOK) GetPayload() *DeleteExpenseWorkflowWorkflowIDOKBody {
	return o.Payload
}

func (o *DeleteExpenseWorkflowWorkflowIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteExpenseWorkflowWorkflowIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteExpenseWorkflowWorkflowIDUnauthorized creates a DeleteExpenseWorkflowWorkflowIDUnauthorized with default headers values
func NewDeleteExpenseWorkflowWorkflowIDUnauthorized() *DeleteExpenseWorkflowWorkflowIDUnauthorized {
	return &DeleteExpenseWorkflowWorkflowIDUnauthorized{}
}

/* DeleteExpenseWorkflowWorkflowIDUnauthorized describes a response with status code 401, with default header values.

APIトークンの値を確認して下さい。
*/
type DeleteExpenseWorkflowWorkflowIDUnauthorized struct {
	Payload *model.ErrorModel
}

func (o *DeleteExpenseWorkflowWorkflowIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /expense/workflow/{workflowID}][%d] deleteExpenseWorkflowWorkflowIdUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteExpenseWorkflowWorkflowIDUnauthorized) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteExpenseWorkflowWorkflowIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteExpenseWorkflowWorkflowIDForbidden creates a DeleteExpenseWorkflowWorkflowIDForbidden with default headers values
func NewDeleteExpenseWorkflowWorkflowIDForbidden() *DeleteExpenseWorkflowWorkflowIDForbidden {
	return &DeleteExpenseWorkflowWorkflowIDForbidden{}
}

/* DeleteExpenseWorkflowWorkflowIDForbidden describes a response with status code 403, with default header values.

APIにアクセスする権限がありません。
*/
type DeleteExpenseWorkflowWorkflowIDForbidden struct {
	Payload *model.ErrorModel
}

func (o *DeleteExpenseWorkflowWorkflowIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /expense/workflow/{workflowID}][%d] deleteExpenseWorkflowWorkflowIdForbidden  %+v", 403, o.Payload)
}
func (o *DeleteExpenseWorkflowWorkflowIDForbidden) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteExpenseWorkflowWorkflowIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteExpenseWorkflowWorkflowIDUnprocessableEntity creates a DeleteExpenseWorkflowWorkflowIDUnprocessableEntity with default headers values
func NewDeleteExpenseWorkflowWorkflowIDUnprocessableEntity() *DeleteExpenseWorkflowWorkflowIDUnprocessableEntity {
	return &DeleteExpenseWorkflowWorkflowIDUnprocessableEntity{}
}

/* DeleteExpenseWorkflowWorkflowIDUnprocessableEntity describes a response with status code 422, with default header values.

パラメータの値を確認して下さい。
*/
type DeleteExpenseWorkflowWorkflowIDUnprocessableEntity struct {
	Payload *model.ErrorModel
}

func (o *DeleteExpenseWorkflowWorkflowIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /expense/workflow/{workflowID}][%d] deleteExpenseWorkflowWorkflowIdUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *DeleteExpenseWorkflowWorkflowIDUnprocessableEntity) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteExpenseWorkflowWorkflowIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteExpenseWorkflowWorkflowIDInternalServerError creates a DeleteExpenseWorkflowWorkflowIDInternalServerError with default headers values
func NewDeleteExpenseWorkflowWorkflowIDInternalServerError() *DeleteExpenseWorkflowWorkflowIDInternalServerError {
	return &DeleteExpenseWorkflowWorkflowIDInternalServerError{}
}

/* DeleteExpenseWorkflowWorkflowIDInternalServerError describes a response with status code 500, with default header values.

APIサーバーの内部的なエラーです。
*/
type DeleteExpenseWorkflowWorkflowIDInternalServerError struct {
	Payload *model.ErrorModel
}

func (o *DeleteExpenseWorkflowWorkflowIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /expense/workflow/{workflowID}][%d] deleteExpenseWorkflowWorkflowIdInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteExpenseWorkflowWorkflowIDInternalServerError) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteExpenseWorkflowWorkflowIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteExpenseWorkflowWorkflowIDOKBody delete expense workflow workflow ID o k body
swagger:model DeleteExpenseWorkflowWorkflowIDOKBody
*/
type DeleteExpenseWorkflowWorkflowIDOKBody struct {

	// response
	Response *DeleteExpenseWorkflowWorkflowIDOKBodyResponse `json:"response,omitempty"`

	// 結果コード
	ResultCode string `json:"result_code,omitempty"`

	// 結果ステータス
	Status bool `json:"status,omitempty"`
}

// Validate validates this delete expense workflow workflow ID o k body
func (o *DeleteExpenseWorkflowWorkflowIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResponse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteExpenseWorkflowWorkflowIDOKBody) validateResponse(formats strfmt.Registry) error {
	if swag.IsZero(o.Response) { // not required
		return nil
	}

	if o.Response != nil {
		if err := o.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteExpenseWorkflowWorkflowIdOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete expense workflow workflow ID o k body based on the context it is used
func (o *DeleteExpenseWorkflowWorkflowIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteExpenseWorkflowWorkflowIDOKBody) contextValidateResponse(ctx context.Context, formats strfmt.Registry) error {

	if o.Response != nil {
		if err := o.Response.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteExpenseWorkflowWorkflowIdOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteExpenseWorkflowWorkflowIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteExpenseWorkflowWorkflowIDOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteExpenseWorkflowWorkflowIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteExpenseWorkflowWorkflowIDOKBodyResponse APIレスポンス
swagger:model DeleteExpenseWorkflowWorkflowIDOKBodyResponse
*/
type DeleteExpenseWorkflowWorkflowIDOKBodyResponse struct {

	// 処理結果
	Result bool `json:"result,omitempty"`
}

// Validate validates this delete expense workflow workflow ID o k body response
func (o *DeleteExpenseWorkflowWorkflowIDOKBodyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete expense workflow workflow ID o k body response based on context it is used
func (o *DeleteExpenseWorkflowWorkflowIDOKBodyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteExpenseWorkflowWorkflowIDOKBodyResponse) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteExpenseWorkflowWorkflowIDOKBodyResponse) UnmarshalBinary(b []byte) error {
	var res DeleteExpenseWorkflowWorkflowIDOKBodyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
