// Code generated by go-swagger; DO NOT EDIT.

package expense_workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutExpenseWorkflowWorkflowIDParams creates a new PutExpenseWorkflowWorkflowIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutExpenseWorkflowWorkflowIDParams() *PutExpenseWorkflowWorkflowIDParams {
	return &PutExpenseWorkflowWorkflowIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutExpenseWorkflowWorkflowIDParamsWithTimeout creates a new PutExpenseWorkflowWorkflowIDParams object
// with the ability to set a timeout on a request.
func NewPutExpenseWorkflowWorkflowIDParamsWithTimeout(timeout time.Duration) *PutExpenseWorkflowWorkflowIDParams {
	return &PutExpenseWorkflowWorkflowIDParams{
		timeout: timeout,
	}
}

// NewPutExpenseWorkflowWorkflowIDParamsWithContext creates a new PutExpenseWorkflowWorkflowIDParams object
// with the ability to set a context for a request.
func NewPutExpenseWorkflowWorkflowIDParamsWithContext(ctx context.Context) *PutExpenseWorkflowWorkflowIDParams {
	return &PutExpenseWorkflowWorkflowIDParams{
		Context: ctx,
	}
}

// NewPutExpenseWorkflowWorkflowIDParamsWithHTTPClient creates a new PutExpenseWorkflowWorkflowIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutExpenseWorkflowWorkflowIDParamsWithHTTPClient(client *http.Client) *PutExpenseWorkflowWorkflowIDParams {
	return &PutExpenseWorkflowWorkflowIDParams{
		HTTPClient: client,
	}
}

/* PutExpenseWorkflowWorkflowIDParams contains all the parameters to send to the API endpoint
   for the put expense workflow workflow ID operation.

   Typically these are written to a http.Request.
*/
type PutExpenseWorkflowWorkflowIDParams struct {

	/* WorkflowID.

	   申請ID
	*/
	WorkflowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put expense workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutExpenseWorkflowWorkflowIDParams) WithDefaults() *PutExpenseWorkflowWorkflowIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put expense workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutExpenseWorkflowWorkflowIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put expense workflow workflow ID params
func (o *PutExpenseWorkflowWorkflowIDParams) WithTimeout(timeout time.Duration) *PutExpenseWorkflowWorkflowIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put expense workflow workflow ID params
func (o *PutExpenseWorkflowWorkflowIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put expense workflow workflow ID params
func (o *PutExpenseWorkflowWorkflowIDParams) WithContext(ctx context.Context) *PutExpenseWorkflowWorkflowIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put expense workflow workflow ID params
func (o *PutExpenseWorkflowWorkflowIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put expense workflow workflow ID params
func (o *PutExpenseWorkflowWorkflowIDParams) WithHTTPClient(client *http.Client) *PutExpenseWorkflowWorkflowIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put expense workflow workflow ID params
func (o *PutExpenseWorkflowWorkflowIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflowID adds the workflowID to the put expense workflow workflow ID params
func (o *PutExpenseWorkflowWorkflowIDParams) WithWorkflowID(workflowID string) *PutExpenseWorkflowWorkflowIDParams {
	o.SetWorkflowID(workflowID)
	return o
}

// SetWorkflowID adds the workflowId to the put expense workflow workflow ID params
func (o *PutExpenseWorkflowWorkflowIDParams) SetWorkflowID(workflowID string) {
	o.WorkflowID = workflowID
}

// WriteToRequest writes these params to a swagger request
func (o *PutExpenseWorkflowWorkflowIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workflowID
	if err := r.SetPathParam("workflowID", o.WorkflowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
