// Code generated by go-swagger; DO NOT EDIT.

package attendances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAttendancesParams creates a new GetAttendancesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAttendancesParams() *GetAttendancesParams {
	return &GetAttendancesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAttendancesParamsWithTimeout creates a new GetAttendancesParams object
// with the ability to set a timeout on a request.
func NewGetAttendancesParamsWithTimeout(timeout time.Duration) *GetAttendancesParams {
	return &GetAttendancesParams{
		timeout: timeout,
	}
}

// NewGetAttendancesParamsWithContext creates a new GetAttendancesParams object
// with the ability to set a context for a request.
func NewGetAttendancesParamsWithContext(ctx context.Context) *GetAttendancesParams {
	return &GetAttendancesParams{
		Context: ctx,
	}
}

// NewGetAttendancesParamsWithHTTPClient creates a new GetAttendancesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAttendancesParamsWithHTTPClient(client *http.Client) *GetAttendancesParams {
	return &GetAttendancesParams{
		HTTPClient: client,
	}
}

/* GetAttendancesParams contains all the parameters to send to the API endpoint
   for the get attendances operation.

   Typically these are written to a http.Request.
*/
type GetAttendancesParams struct {

	/* Email.

	   メールアドレス
	*/
	Email string

	/* Term.

	   年月（YYYYMM）。指定された年月のデータを返します。省略時は当月のデータを返します。
	*/
	Term *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get attendances params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAttendancesParams) WithDefaults() *GetAttendancesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get attendances params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAttendancesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get attendances params
func (o *GetAttendancesParams) WithTimeout(timeout time.Duration) *GetAttendancesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get attendances params
func (o *GetAttendancesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get attendances params
func (o *GetAttendancesParams) WithContext(ctx context.Context) *GetAttendancesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get attendances params
func (o *GetAttendancesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get attendances params
func (o *GetAttendancesParams) WithHTTPClient(client *http.Client) *GetAttendancesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get attendances params
func (o *GetAttendancesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the get attendances params
func (o *GetAttendancesParams) WithEmail(email string) *GetAttendancesParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the get attendances params
func (o *GetAttendancesParams) SetEmail(email string) {
	o.Email = email
}

// WithTerm adds the term to the get attendances params
func (o *GetAttendancesParams) WithTerm(term *string) *GetAttendancesParams {
	o.SetTerm(term)
	return o
}

// SetTerm adds the term to the get attendances params
func (o *GetAttendancesParams) SetTerm(term *string) {
	o.Term = term
}

// WriteToRequest writes these params to a swagger request
func (o *GetAttendancesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param email
	qrEmail := o.Email
	qEmail := qrEmail
	if qEmail != "" {

		if err := r.SetQueryParam("email", qEmail); err != nil {
			return err
		}
	}

	if o.Term != nil {

		// query param term
		var qrTerm string

		if o.Term != nil {
			qrTerm = *o.Term
		}
		qTerm := qrTerm
		if qTerm != "" {

			if err := r.SetQueryParam("term", qTerm); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
