// Code generated by go-swagger; DO NOT EDIT.

package kinkone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DepartmentModel 部署・店舗情報
//
// swagger:model departmentModel
type DepartmentModel struct {

	// 登録日時
	Created string `json:"created,omitempty"`

	// 部署名
	Name string `json:"name,omitempty"`
}

// Validate validates this department model
func (m *DepartmentModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this department model based on context it is used
func (m *DepartmentModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DepartmentModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DepartmentModel) UnmarshalBinary(b []byte) error {
	var res DepartmentModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
