// Code generated by go-swagger; DO NOT EDIT.

package kinkone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HourlyPaidLeaveWorkflowModel 時間休の申請
//
// swagger:model hourlyPaidLeaveWorkflowModel
type HourlyPaidLeaveWorkflowModel struct {

	// 申請日
	AppliedDate string `json:"applied_date,omitempty"`

	// 差戻しコメント
	BackComment string `json:"back_comment,omitempty"`

	// 申請コメント
	Comment string `json:"comment,omitempty"`

	// 承認日
	ConfirmedDate string `json:"confirmed_date,omitempty"`

	// メールアドレス
	Email string `json:"email,omitempty"`

	// 姓
	FamilyName string `json:"family_name,omitempty"`

	// 名
	FirstName string `json:"first_name,omitempty"`

	// 時間
	Hours string `json:"hours,omitempty"`

	// ID
	ID string `json:"id,omitempty"`

	// 申請ステータス（1: 差戻し, 2: 申請済み, 3: 承認）
	Status int64 `json:"status,omitempty"`

	// 従業員番号
	UserNumber string `json:"user_number,omitempty"`

	// 出勤日
	WorkDay string `json:"work_day,omitempty"`
}

// Validate validates this hourly paid leave workflow model
func (m *HourlyPaidLeaveWorkflowModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hourly paid leave workflow model based on context it is used
func (m *HourlyPaidLeaveWorkflowModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HourlyPaidLeaveWorkflowModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HourlyPaidLeaveWorkflowModel) UnmarshalBinary(b []byte) error {
	var res HourlyPaidLeaveWorkflowModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
