// Code generated by go-swagger; DO NOT EDIT.

package kinkone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kekecone/go-kincone/kinkone/attendance"
	"github.com/kekecone/go-kincone/kinkone/attendance_flags"
	"github.com/kekecone/go-kincone/kinkone/attendance_hourly_paid_leave"
	"github.com/kekecone/go-kincone/kinkone/attendance_workflows"
	"github.com/kekecone/go-kincone/kinkone/attendances"
	"github.com/kekecone/go-kincone/kinkone/compensation_workflows"
	"github.com/kekecone/go-kincone/kinkone/departments"
	"github.com/kekecone/go-kincone/kinkone/expense_workflows"
	"github.com/kekecone/go-kincone/kinkone/expenses"
	"github.com/kekecone/go-kincone/kinkone/flag_workflows"
	"github.com/kekecone/go-kincone/kinkone/hourly_paid_leave_workflows"
	"github.com/kekecone/go-kincone/kinkone/punch"
	"github.com/kekecone/go-kincone/kinkone/users"
)

// Default kinkone HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.kincone.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new kinkone HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Kinkone {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new kinkone HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Kinkone {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new kinkone client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Kinkone {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Kinkone)
	cli.Transport = transport
	cli.Attendance = attendance.New(transport, formats)
	cli.AttendanceFlags = attendance_flags.New(transport, formats)
	cli.AttendanceHourlyPaidLeave = attendance_hourly_paid_leave.New(transport, formats)
	cli.AttendanceWorkflows = attendance_workflows.New(transport, formats)
	cli.Attendances = attendances.New(transport, formats)
	cli.CompensationWorkflows = compensation_workflows.New(transport, formats)
	cli.Departments = departments.New(transport, formats)
	cli.ExpenseWorkflows = expense_workflows.New(transport, formats)
	cli.Expenses = expenses.New(transport, formats)
	cli.FlagWorkflows = flag_workflows.New(transport, formats)
	cli.HourlyPaidLeaveWorkflows = hourly_paid_leave_workflows.New(transport, formats)
	cli.Punch = punch.New(transport, formats)
	cli.Users = users.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Kinkone is a client for kinkone
type Kinkone struct {
	Attendance attendance.ClientService

	AttendanceFlags attendance_flags.ClientService

	AttendanceHourlyPaidLeave attendance_hourly_paid_leave.ClientService

	AttendanceWorkflows attendance_workflows.ClientService

	Attendances attendances.ClientService

	CompensationWorkflows compensation_workflows.ClientService

	Departments departments.ClientService

	ExpenseWorkflows expense_workflows.ClientService

	Expenses expenses.ClientService

	FlagWorkflows flag_workflows.ClientService

	HourlyPaidLeaveWorkflows hourly_paid_leave_workflows.ClientService

	Punch punch.ClientService

	Users users.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Kinkone) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Attendance.SetTransport(transport)
	c.AttendanceFlags.SetTransport(transport)
	c.AttendanceHourlyPaidLeave.SetTransport(transport)
	c.AttendanceWorkflows.SetTransport(transport)
	c.Attendances.SetTransport(transport)
	c.CompensationWorkflows.SetTransport(transport)
	c.Departments.SetTransport(transport)
	c.ExpenseWorkflows.SetTransport(transport)
	c.Expenses.SetTransport(transport)
	c.FlagWorkflows.SetTransport(transport)
	c.HourlyPaidLeaveWorkflows.SetTransport(transport)
	c.Punch.SetTransport(transport)
	c.Users.SetTransport(transport)
}
