// Code generated by go-swagger; DO NOT EDIT.

package attendance_hourly_paid_leave

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kekecone/go-kincone/kinkone/model"
)

// DeleteAttendanceHourlyPaidLeaveReader is a Reader for the DeleteAttendanceHourlyPaidLeave structure.
type DeleteAttendanceHourlyPaidLeaveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAttendanceHourlyPaidLeaveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAttendanceHourlyPaidLeaveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteAttendanceHourlyPaidLeaveUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAttendanceHourlyPaidLeaveForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteAttendanceHourlyPaidLeaveUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAttendanceHourlyPaidLeaveInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAttendanceHourlyPaidLeaveOK creates a DeleteAttendanceHourlyPaidLeaveOK with default headers values
func NewDeleteAttendanceHourlyPaidLeaveOK() *DeleteAttendanceHourlyPaidLeaveOK {
	return &DeleteAttendanceHourlyPaidLeaveOK{}
}

/* DeleteAttendanceHourlyPaidLeaveOK describes a response with status code 200, with default header values.

正常時
*/
type DeleteAttendanceHourlyPaidLeaveOK struct {
	Payload *DeleteAttendanceHourlyPaidLeaveOKBody
}

func (o *DeleteAttendanceHourlyPaidLeaveOK) Error() string {
	return fmt.Sprintf("[DELETE /attendance/hourly_paid_leave][%d] deleteAttendanceHourlyPaidLeaveOK  %+v", 200, o.Payload)
}
func (o *DeleteAttendanceHourlyPaidLeaveOK) GetPayload() *DeleteAttendanceHourlyPaidLeaveOKBody {
	return o.Payload
}

func (o *DeleteAttendanceHourlyPaidLeaveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteAttendanceHourlyPaidLeaveOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceHourlyPaidLeaveUnauthorized creates a DeleteAttendanceHourlyPaidLeaveUnauthorized with default headers values
func NewDeleteAttendanceHourlyPaidLeaveUnauthorized() *DeleteAttendanceHourlyPaidLeaveUnauthorized {
	return &DeleteAttendanceHourlyPaidLeaveUnauthorized{}
}

/* DeleteAttendanceHourlyPaidLeaveUnauthorized describes a response with status code 401, with default header values.

APIトークンの値を確認して下さい。
*/
type DeleteAttendanceHourlyPaidLeaveUnauthorized struct {
	Payload *model.ErrorModel
}

func (o *DeleteAttendanceHourlyPaidLeaveUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /attendance/hourly_paid_leave][%d] deleteAttendanceHourlyPaidLeaveUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteAttendanceHourlyPaidLeaveUnauthorized) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceHourlyPaidLeaveUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceHourlyPaidLeaveForbidden creates a DeleteAttendanceHourlyPaidLeaveForbidden with default headers values
func NewDeleteAttendanceHourlyPaidLeaveForbidden() *DeleteAttendanceHourlyPaidLeaveForbidden {
	return &DeleteAttendanceHourlyPaidLeaveForbidden{}
}

/* DeleteAttendanceHourlyPaidLeaveForbidden describes a response with status code 403, with default header values.

APIにアクセスする権限がありません。
*/
type DeleteAttendanceHourlyPaidLeaveForbidden struct {
	Payload *model.ErrorModel
}

func (o *DeleteAttendanceHourlyPaidLeaveForbidden) Error() string {
	return fmt.Sprintf("[DELETE /attendance/hourly_paid_leave][%d] deleteAttendanceHourlyPaidLeaveForbidden  %+v", 403, o.Payload)
}
func (o *DeleteAttendanceHourlyPaidLeaveForbidden) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceHourlyPaidLeaveForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceHourlyPaidLeaveUnprocessableEntity creates a DeleteAttendanceHourlyPaidLeaveUnprocessableEntity with default headers values
func NewDeleteAttendanceHourlyPaidLeaveUnprocessableEntity() *DeleteAttendanceHourlyPaidLeaveUnprocessableEntity {
	return &DeleteAttendanceHourlyPaidLeaveUnprocessableEntity{}
}

/* DeleteAttendanceHourlyPaidLeaveUnprocessableEntity describes a response with status code 422, with default header values.

パラメータの値を確認して下さい。
*/
type DeleteAttendanceHourlyPaidLeaveUnprocessableEntity struct {
	Payload *model.ErrorModel
}

func (o *DeleteAttendanceHourlyPaidLeaveUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /attendance/hourly_paid_leave][%d] deleteAttendanceHourlyPaidLeaveUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *DeleteAttendanceHourlyPaidLeaveUnprocessableEntity) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceHourlyPaidLeaveUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceHourlyPaidLeaveInternalServerError creates a DeleteAttendanceHourlyPaidLeaveInternalServerError with default headers values
func NewDeleteAttendanceHourlyPaidLeaveInternalServerError() *DeleteAttendanceHourlyPaidLeaveInternalServerError {
	return &DeleteAttendanceHourlyPaidLeaveInternalServerError{}
}

/* DeleteAttendanceHourlyPaidLeaveInternalServerError describes a response with status code 500, with default header values.

APIサーバーの内部的なエラーです。
*/
type DeleteAttendanceHourlyPaidLeaveInternalServerError struct {
	Payload *model.ErrorModel
}

func (o *DeleteAttendanceHourlyPaidLeaveInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /attendance/hourly_paid_leave][%d] deleteAttendanceHourlyPaidLeaveInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteAttendanceHourlyPaidLeaveInternalServerError) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceHourlyPaidLeaveInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteAttendanceHourlyPaidLeaveOKBody delete attendance hourly paid leave o k body
swagger:model DeleteAttendanceHourlyPaidLeaveOKBody
*/
type DeleteAttendanceHourlyPaidLeaveOKBody struct {

	// response
	Response *DeleteAttendanceHourlyPaidLeaveOKBodyResponse `json:"response,omitempty"`

	// 結果コード
	ResultCode string `json:"result_code,omitempty"`

	// 結果ステータス
	Status bool `json:"status,omitempty"`
}

// Validate validates this delete attendance hourly paid leave o k body
func (o *DeleteAttendanceHourlyPaidLeaveOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResponse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceHourlyPaidLeaveOKBody) validateResponse(formats strfmt.Registry) error {
	if swag.IsZero(o.Response) { // not required
		return nil
	}

	if o.Response != nil {
		if err := o.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceHourlyPaidLeaveOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete attendance hourly paid leave o k body based on the context it is used
func (o *DeleteAttendanceHourlyPaidLeaveOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceHourlyPaidLeaveOKBody) contextValidateResponse(ctx context.Context, formats strfmt.Registry) error {

	if o.Response != nil {
		if err := o.Response.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceHourlyPaidLeaveOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteAttendanceHourlyPaidLeaveOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteAttendanceHourlyPaidLeaveOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteAttendanceHourlyPaidLeaveOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteAttendanceHourlyPaidLeaveOKBodyResponse APIレスポンス
swagger:model DeleteAttendanceHourlyPaidLeaveOKBodyResponse
*/
type DeleteAttendanceHourlyPaidLeaveOKBodyResponse struct {

	// attendance
	Attendance *model.AttendanceModel `json:"attendance,omitempty"`
}

// Validate validates this delete attendance hourly paid leave o k body response
func (o *DeleteAttendanceHourlyPaidLeaveOKBodyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAttendance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceHourlyPaidLeaveOKBodyResponse) validateAttendance(formats strfmt.Registry) error {
	if swag.IsZero(o.Attendance) { // not required
		return nil
	}

	if o.Attendance != nil {
		if err := o.Attendance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceHourlyPaidLeaveOK" + "." + "response" + "." + "attendance")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete attendance hourly paid leave o k body response based on the context it is used
func (o *DeleteAttendanceHourlyPaidLeaveOKBodyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAttendance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceHourlyPaidLeaveOKBodyResponse) contextValidateAttendance(ctx context.Context, formats strfmt.Registry) error {

	if o.Attendance != nil {
		if err := o.Attendance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceHourlyPaidLeaveOK" + "." + "response" + "." + "attendance")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteAttendanceHourlyPaidLeaveOKBodyResponse) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteAttendanceHourlyPaidLeaveOKBodyResponse) UnmarshalBinary(b []byte) error {
	var res DeleteAttendanceHourlyPaidLeaveOKBodyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
