// Code generated by go-swagger; DO NOT EDIT.

package attendance_hourly_paid_leave

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAttendanceHourlyPaidLeaveParams creates a new DeleteAttendanceHourlyPaidLeaveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAttendanceHourlyPaidLeaveParams() *DeleteAttendanceHourlyPaidLeaveParams {
	return &DeleteAttendanceHourlyPaidLeaveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAttendanceHourlyPaidLeaveParamsWithTimeout creates a new DeleteAttendanceHourlyPaidLeaveParams object
// with the ability to set a timeout on a request.
func NewDeleteAttendanceHourlyPaidLeaveParamsWithTimeout(timeout time.Duration) *DeleteAttendanceHourlyPaidLeaveParams {
	return &DeleteAttendanceHourlyPaidLeaveParams{
		timeout: timeout,
	}
}

// NewDeleteAttendanceHourlyPaidLeaveParamsWithContext creates a new DeleteAttendanceHourlyPaidLeaveParams object
// with the ability to set a context for a request.
func NewDeleteAttendanceHourlyPaidLeaveParamsWithContext(ctx context.Context) *DeleteAttendanceHourlyPaidLeaveParams {
	return &DeleteAttendanceHourlyPaidLeaveParams{
		Context: ctx,
	}
}

// NewDeleteAttendanceHourlyPaidLeaveParamsWithHTTPClient creates a new DeleteAttendanceHourlyPaidLeaveParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAttendanceHourlyPaidLeaveParamsWithHTTPClient(client *http.Client) *DeleteAttendanceHourlyPaidLeaveParams {
	return &DeleteAttendanceHourlyPaidLeaveParams{
		HTTPClient: client,
	}
}

/* DeleteAttendanceHourlyPaidLeaveParams contains all the parameters to send to the API endpoint
   for the delete attendance hourly paid leave operation.

   Typically these are written to a http.Request.
*/
type DeleteAttendanceHourlyPaidLeaveParams struct {

	/* Date.

	   日付（YYYY-MM-DD）
	*/
	Date string

	/* Email.

	   メールアドレス
	*/
	Email string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete attendance hourly paid leave params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAttendanceHourlyPaidLeaveParams) WithDefaults() *DeleteAttendanceHourlyPaidLeaveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete attendance hourly paid leave params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAttendanceHourlyPaidLeaveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) WithTimeout(timeout time.Duration) *DeleteAttendanceHourlyPaidLeaveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) WithContext(ctx context.Context) *DeleteAttendanceHourlyPaidLeaveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) WithHTTPClient(client *http.Client) *DeleteAttendanceHourlyPaidLeaveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDate adds the date to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) WithDate(date string) *DeleteAttendanceHourlyPaidLeaveParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) SetDate(date string) {
	o.Date = date
}

// WithEmail adds the email to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) WithEmail(email string) *DeleteAttendanceHourlyPaidLeaveParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the delete attendance hourly paid leave params
func (o *DeleteAttendanceHourlyPaidLeaveParams) SetEmail(email string) {
	o.Email = email
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAttendanceHourlyPaidLeaveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param date
	frDate := o.Date
	fDate := frDate
	if fDate != "" {
		if err := r.SetFormParam("date", fDate); err != nil {
			return err
		}
	}

	// form param email
	frEmail := o.Email
	fEmail := frEmail
	if fEmail != "" {
		if err := r.SetFormParam("email", fEmail); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
