// Code generated by go-swagger; DO NOT EDIT.

package attendance_hourly_paid_leave

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kekecone/go-kincone/kinkone"
)

// PostAttendanceHourlyPaidLeaveReader is a Reader for the PostAttendanceHourlyPaidLeave structure.
type PostAttendanceHourlyPaidLeaveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAttendanceHourlyPaidLeaveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAttendanceHourlyPaidLeaveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostAttendanceHourlyPaidLeaveUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAttendanceHourlyPaidLeaveForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAttendanceHourlyPaidLeaveUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAttendanceHourlyPaidLeaveInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAttendanceHourlyPaidLeaveOK creates a PostAttendanceHourlyPaidLeaveOK with default headers values
func NewPostAttendanceHourlyPaidLeaveOK() *PostAttendanceHourlyPaidLeaveOK {
	return &PostAttendanceHourlyPaidLeaveOK{}
}

/* PostAttendanceHourlyPaidLeaveOK describes a response with status code 200, with default header values.

正常時
*/
type PostAttendanceHourlyPaidLeaveOK struct {
	Payload *PostAttendanceHourlyPaidLeaveOKBody
}

func (o *PostAttendanceHourlyPaidLeaveOK) Error() string {
	return fmt.Sprintf("[POST /attendance/hourly_paid_leave][%d] postAttendanceHourlyPaidLeaveOK  %+v", 200, o.Payload)
}
func (o *PostAttendanceHourlyPaidLeaveOK) GetPayload() *PostAttendanceHourlyPaidLeaveOKBody {
	return o.Payload
}

func (o *PostAttendanceHourlyPaidLeaveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostAttendanceHourlyPaidLeaveOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAttendanceHourlyPaidLeaveUnauthorized creates a PostAttendanceHourlyPaidLeaveUnauthorized with default headers values
func NewPostAttendanceHourlyPaidLeaveUnauthorized() *PostAttendanceHourlyPaidLeaveUnauthorized {
	return &PostAttendanceHourlyPaidLeaveUnauthorized{}
}

/* PostAttendanceHourlyPaidLeaveUnauthorized describes a response with status code 401, with default header values.

APIトークンの値を確認して下さい。
*/
type PostAttendanceHourlyPaidLeaveUnauthorized struct {
	Payload *kinkone.ErrorModel
}

func (o *PostAttendanceHourlyPaidLeaveUnauthorized) Error() string {
	return fmt.Sprintf("[POST /attendance/hourly_paid_leave][%d] postAttendanceHourlyPaidLeaveUnauthorized  %+v", 401, o.Payload)
}
func (o *PostAttendanceHourlyPaidLeaveUnauthorized) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *PostAttendanceHourlyPaidLeaveUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAttendanceHourlyPaidLeaveForbidden creates a PostAttendanceHourlyPaidLeaveForbidden with default headers values
func NewPostAttendanceHourlyPaidLeaveForbidden() *PostAttendanceHourlyPaidLeaveForbidden {
	return &PostAttendanceHourlyPaidLeaveForbidden{}
}

/* PostAttendanceHourlyPaidLeaveForbidden describes a response with status code 403, with default header values.

APIにアクセスする権限がありません。
*/
type PostAttendanceHourlyPaidLeaveForbidden struct {
	Payload *kinkone.ErrorModel
}

func (o *PostAttendanceHourlyPaidLeaveForbidden) Error() string {
	return fmt.Sprintf("[POST /attendance/hourly_paid_leave][%d] postAttendanceHourlyPaidLeaveForbidden  %+v", 403, o.Payload)
}
func (o *PostAttendanceHourlyPaidLeaveForbidden) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *PostAttendanceHourlyPaidLeaveForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAttendanceHourlyPaidLeaveUnprocessableEntity creates a PostAttendanceHourlyPaidLeaveUnprocessableEntity with default headers values
func NewPostAttendanceHourlyPaidLeaveUnprocessableEntity() *PostAttendanceHourlyPaidLeaveUnprocessableEntity {
	return &PostAttendanceHourlyPaidLeaveUnprocessableEntity{}
}

/* PostAttendanceHourlyPaidLeaveUnprocessableEntity describes a response with status code 422, with default header values.

パラメータの値を確認して下さい。
*/
type PostAttendanceHourlyPaidLeaveUnprocessableEntity struct {
	Payload *kinkone.ErrorModel
}

func (o *PostAttendanceHourlyPaidLeaveUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /attendance/hourly_paid_leave][%d] postAttendanceHourlyPaidLeaveUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *PostAttendanceHourlyPaidLeaveUnprocessableEntity) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *PostAttendanceHourlyPaidLeaveUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAttendanceHourlyPaidLeaveInternalServerError creates a PostAttendanceHourlyPaidLeaveInternalServerError with default headers values
func NewPostAttendanceHourlyPaidLeaveInternalServerError() *PostAttendanceHourlyPaidLeaveInternalServerError {
	return &PostAttendanceHourlyPaidLeaveInternalServerError{}
}

/* PostAttendanceHourlyPaidLeaveInternalServerError describes a response with status code 500, with default header values.

APIサーバーの内部的なエラーです。
*/
type PostAttendanceHourlyPaidLeaveInternalServerError struct {
	Payload *kinkone.ErrorModel
}

func (o *PostAttendanceHourlyPaidLeaveInternalServerError) Error() string {
	return fmt.Sprintf("[POST /attendance/hourly_paid_leave][%d] postAttendanceHourlyPaidLeaveInternalServerError  %+v", 500, o.Payload)
}
func (o *PostAttendanceHourlyPaidLeaveInternalServerError) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *PostAttendanceHourlyPaidLeaveInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostAttendanceHourlyPaidLeaveOKBody post attendance hourly paid leave o k body
swagger:model PostAttendanceHourlyPaidLeaveOKBody
*/
type PostAttendanceHourlyPaidLeaveOKBody struct {

	// response
	Response *PostAttendanceHourlyPaidLeaveOKBodyResponse `json:"response,omitempty"`

	// 結果コード
	ResultCode string `json:"result_code,omitempty"`

	// 結果ステータス
	Status bool `json:"status,omitempty"`
}

// Validate validates this post attendance hourly paid leave o k body
func (o *PostAttendanceHourlyPaidLeaveOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResponse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostAttendanceHourlyPaidLeaveOKBody) validateResponse(formats strfmt.Registry) error {
	if swag.IsZero(o.Response) { // not required
		return nil
	}

	if o.Response != nil {
		if err := o.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postAttendanceHourlyPaidLeaveOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post attendance hourly paid leave o k body based on the context it is used
func (o *PostAttendanceHourlyPaidLeaveOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostAttendanceHourlyPaidLeaveOKBody) contextValidateResponse(ctx context.Context, formats strfmt.Registry) error {

	if o.Response != nil {
		if err := o.Response.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postAttendanceHourlyPaidLeaveOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostAttendanceHourlyPaidLeaveOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAttendanceHourlyPaidLeaveOKBody) UnmarshalBinary(b []byte) error {
	var res PostAttendanceHourlyPaidLeaveOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostAttendanceHourlyPaidLeaveOKBodyResponse APIレスポンス
swagger:model PostAttendanceHourlyPaidLeaveOKBodyResponse
*/
type PostAttendanceHourlyPaidLeaveOKBodyResponse struct {

	// attendance
	Attendance *kinkone.AttendanceModel `json:"attendance,omitempty"`
}

// Validate validates this post attendance hourly paid leave o k body response
func (o *PostAttendanceHourlyPaidLeaveOKBodyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAttendance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostAttendanceHourlyPaidLeaveOKBodyResponse) validateAttendance(formats strfmt.Registry) error {
	if swag.IsZero(o.Attendance) { // not required
		return nil
	}

	if o.Attendance != nil {
		if err := o.Attendance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postAttendanceHourlyPaidLeaveOK" + "." + "response" + "." + "attendance")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post attendance hourly paid leave o k body response based on the context it is used
func (o *PostAttendanceHourlyPaidLeaveOKBodyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAttendance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostAttendanceHourlyPaidLeaveOKBodyResponse) contextValidateAttendance(ctx context.Context, formats strfmt.Registry) error {

	if o.Attendance != nil {
		if err := o.Attendance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postAttendanceHourlyPaidLeaveOK" + "." + "response" + "." + "attendance")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostAttendanceHourlyPaidLeaveOKBodyResponse) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAttendanceHourlyPaidLeaveOKBodyResponse) UnmarshalBinary(b []byte) error {
	var res PostAttendanceHourlyPaidLeaveOKBodyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
