// Code generated by go-swagger; DO NOT EDIT.

package attendance_hourly_paid_leave

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostAttendanceHourlyPaidLeaveParams creates a new PostAttendanceHourlyPaidLeaveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAttendanceHourlyPaidLeaveParams() *PostAttendanceHourlyPaidLeaveParams {
	return &PostAttendanceHourlyPaidLeaveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAttendanceHourlyPaidLeaveParamsWithTimeout creates a new PostAttendanceHourlyPaidLeaveParams object
// with the ability to set a timeout on a request.
func NewPostAttendanceHourlyPaidLeaveParamsWithTimeout(timeout time.Duration) *PostAttendanceHourlyPaidLeaveParams {
	return &PostAttendanceHourlyPaidLeaveParams{
		timeout: timeout,
	}
}

// NewPostAttendanceHourlyPaidLeaveParamsWithContext creates a new PostAttendanceHourlyPaidLeaveParams object
// with the ability to set a context for a request.
func NewPostAttendanceHourlyPaidLeaveParamsWithContext(ctx context.Context) *PostAttendanceHourlyPaidLeaveParams {
	return &PostAttendanceHourlyPaidLeaveParams{
		Context: ctx,
	}
}

// NewPostAttendanceHourlyPaidLeaveParamsWithHTTPClient creates a new PostAttendanceHourlyPaidLeaveParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAttendanceHourlyPaidLeaveParamsWithHTTPClient(client *http.Client) *PostAttendanceHourlyPaidLeaveParams {
	return &PostAttendanceHourlyPaidLeaveParams{
		HTTPClient: client,
	}
}

/* PostAttendanceHourlyPaidLeaveParams contains all the parameters to send to the API endpoint
   for the post attendance hourly paid leave operation.

   Typically these are written to a http.Request.
*/
type PostAttendanceHourlyPaidLeaveParams struct {

	/* Date.

	   日付（YYYY-MM-DD）
	*/
	Date string

	/* Email.

	   メールアドレス
	*/
	Email string

	/* Hours.

	   時間休の取得時間
	*/
	Hours int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post attendance hourly paid leave params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAttendanceHourlyPaidLeaveParams) WithDefaults() *PostAttendanceHourlyPaidLeaveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post attendance hourly paid leave params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAttendanceHourlyPaidLeaveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) WithTimeout(timeout time.Duration) *PostAttendanceHourlyPaidLeaveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) WithContext(ctx context.Context) *PostAttendanceHourlyPaidLeaveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) WithHTTPClient(client *http.Client) *PostAttendanceHourlyPaidLeaveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDate adds the date to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) WithDate(date string) *PostAttendanceHourlyPaidLeaveParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) SetDate(date string) {
	o.Date = date
}

// WithEmail adds the email to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) WithEmail(email string) *PostAttendanceHourlyPaidLeaveParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) SetEmail(email string) {
	o.Email = email
}

// WithHours adds the hours to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) WithHours(hours int64) *PostAttendanceHourlyPaidLeaveParams {
	o.SetHours(hours)
	return o
}

// SetHours adds the hours to the post attendance hourly paid leave params
func (o *PostAttendanceHourlyPaidLeaveParams) SetHours(hours int64) {
	o.Hours = hours
}

// WriteToRequest writes these params to a swagger request
func (o *PostAttendanceHourlyPaidLeaveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param date
	frDate := o.Date
	fDate := frDate
	if fDate != "" {
		if err := r.SetFormParam("date", fDate); err != nil {
			return err
		}
	}

	// form param email
	frEmail := o.Email
	fEmail := frEmail
	if fEmail != "" {
		if err := r.SetFormParam("email", fEmail); err != nil {
			return err
		}
	}

	// form param hours
	frHours := o.Hours
	fHours := swag.FormatInt64(frHours)
	if fHours != "" {
		if err := r.SetFormParam("hours", fHours); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
