// Code generated by go-swagger; DO NOT EDIT.

package attendance_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kekecone/go-kincone/kinkone/model"
)

// DeleteAttendanceFlagsReader is a Reader for the DeleteAttendanceFlags structure.
type DeleteAttendanceFlagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAttendanceFlagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAttendanceFlagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteAttendanceFlagsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAttendanceFlagsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteAttendanceFlagsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAttendanceFlagsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAttendanceFlagsOK creates a DeleteAttendanceFlagsOK with default headers values
func NewDeleteAttendanceFlagsOK() *DeleteAttendanceFlagsOK {
	return &DeleteAttendanceFlagsOK{}
}

/* DeleteAttendanceFlagsOK describes a response with status code 200, with default header values.

正常時
*/
type DeleteAttendanceFlagsOK struct {
	Payload *DeleteAttendanceFlagsOKBody
}

func (o *DeleteAttendanceFlagsOK) Error() string {
	return fmt.Sprintf("[DELETE /attendance/flags][%d] deleteAttendanceFlagsOK  %+v", 200, o.Payload)
}
func (o *DeleteAttendanceFlagsOK) GetPayload() *DeleteAttendanceFlagsOKBody {
	return o.Payload
}

func (o *DeleteAttendanceFlagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteAttendanceFlagsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceFlagsUnauthorized creates a DeleteAttendanceFlagsUnauthorized with default headers values
func NewDeleteAttendanceFlagsUnauthorized() *DeleteAttendanceFlagsUnauthorized {
	return &DeleteAttendanceFlagsUnauthorized{}
}

/* DeleteAttendanceFlagsUnauthorized describes a response with status code 401, with default header values.

APIトークンの値を確認して下さい。
*/
type DeleteAttendanceFlagsUnauthorized struct {
	Payload *model.ErrorModel
}

func (o *DeleteAttendanceFlagsUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /attendance/flags][%d] deleteAttendanceFlagsUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteAttendanceFlagsUnauthorized) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceFlagsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceFlagsForbidden creates a DeleteAttendanceFlagsForbidden with default headers values
func NewDeleteAttendanceFlagsForbidden() *DeleteAttendanceFlagsForbidden {
	return &DeleteAttendanceFlagsForbidden{}
}

/* DeleteAttendanceFlagsForbidden describes a response with status code 403, with default header values.

APIにアクセスする権限がありません。
*/
type DeleteAttendanceFlagsForbidden struct {
	Payload *model.ErrorModel
}

func (o *DeleteAttendanceFlagsForbidden) Error() string {
	return fmt.Sprintf("[DELETE /attendance/flags][%d] deleteAttendanceFlagsForbidden  %+v", 403, o.Payload)
}
func (o *DeleteAttendanceFlagsForbidden) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceFlagsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceFlagsUnprocessableEntity creates a DeleteAttendanceFlagsUnprocessableEntity with default headers values
func NewDeleteAttendanceFlagsUnprocessableEntity() *DeleteAttendanceFlagsUnprocessableEntity {
	return &DeleteAttendanceFlagsUnprocessableEntity{}
}

/* DeleteAttendanceFlagsUnprocessableEntity describes a response with status code 422, with default header values.

パラメータの値を確認して下さい。
*/
type DeleteAttendanceFlagsUnprocessableEntity struct {
	Payload *model.ErrorModel
}

func (o *DeleteAttendanceFlagsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /attendance/flags][%d] deleteAttendanceFlagsUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *DeleteAttendanceFlagsUnprocessableEntity) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceFlagsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceFlagsInternalServerError creates a DeleteAttendanceFlagsInternalServerError with default headers values
func NewDeleteAttendanceFlagsInternalServerError() *DeleteAttendanceFlagsInternalServerError {
	return &DeleteAttendanceFlagsInternalServerError{}
}

/* DeleteAttendanceFlagsInternalServerError describes a response with status code 500, with default header values.

APIサーバーの内部的なエラーです。
*/
type DeleteAttendanceFlagsInternalServerError struct {
	Payload *model.ErrorModel
}

func (o *DeleteAttendanceFlagsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /attendance/flags][%d] deleteAttendanceFlagsInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteAttendanceFlagsInternalServerError) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceFlagsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteAttendanceFlagsOKBody delete attendance flags o k body
swagger:model DeleteAttendanceFlagsOKBody
*/
type DeleteAttendanceFlagsOKBody struct {

	// response
	Response *DeleteAttendanceFlagsOKBodyResponse `json:"response,omitempty"`

	// 結果コード
	ResultCode string `json:"result_code,omitempty"`

	// 結果ステータス
	Status bool `json:"status,omitempty"`
}

// Validate validates this delete attendance flags o k body
func (o *DeleteAttendanceFlagsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResponse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceFlagsOKBody) validateResponse(formats strfmt.Registry) error {
	if swag.IsZero(o.Response) { // not required
		return nil
	}

	if o.Response != nil {
		if err := o.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceFlagsOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete attendance flags o k body based on the context it is used
func (o *DeleteAttendanceFlagsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceFlagsOKBody) contextValidateResponse(ctx context.Context, formats strfmt.Registry) error {

	if o.Response != nil {
		if err := o.Response.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceFlagsOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteAttendanceFlagsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteAttendanceFlagsOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteAttendanceFlagsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteAttendanceFlagsOKBodyResponse APIレスポンス
swagger:model DeleteAttendanceFlagsOKBodyResponse
*/
type DeleteAttendanceFlagsOKBodyResponse struct {

	// attendance
	Attendance *model.AttendanceModel `json:"attendance,omitempty"`
}

// Validate validates this delete attendance flags o k body response
func (o *DeleteAttendanceFlagsOKBodyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAttendance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceFlagsOKBodyResponse) validateAttendance(formats strfmt.Registry) error {
	if swag.IsZero(o.Attendance) { // not required
		return nil
	}

	if o.Attendance != nil {
		if err := o.Attendance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceFlagsOK" + "." + "response" + "." + "attendance")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete attendance flags o k body response based on the context it is used
func (o *DeleteAttendanceFlagsOKBodyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAttendance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceFlagsOKBodyResponse) contextValidateAttendance(ctx context.Context, formats strfmt.Registry) error {

	if o.Attendance != nil {
		if err := o.Attendance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceFlagsOK" + "." + "response" + "." + "attendance")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteAttendanceFlagsOKBodyResponse) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteAttendanceFlagsOKBodyResponse) UnmarshalBinary(b []byte) error {
	var res DeleteAttendanceFlagsOKBodyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
