// Code generated by go-swagger; DO NOT EDIT.

package hourly_paid_leave_workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteHourlyPaidLeaveWorkflowWorkflowIDParams creates a new DeleteHourlyPaidLeaveWorkflowWorkflowIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteHourlyPaidLeaveWorkflowWorkflowIDParams() *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	return &DeleteHourlyPaidLeaveWorkflowWorkflowIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteHourlyPaidLeaveWorkflowWorkflowIDParamsWithTimeout creates a new DeleteHourlyPaidLeaveWorkflowWorkflowIDParams object
// with the ability to set a timeout on a request.
func NewDeleteHourlyPaidLeaveWorkflowWorkflowIDParamsWithTimeout(timeout time.Duration) *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	return &DeleteHourlyPaidLeaveWorkflowWorkflowIDParams{
		timeout: timeout,
	}
}

// NewDeleteHourlyPaidLeaveWorkflowWorkflowIDParamsWithContext creates a new DeleteHourlyPaidLeaveWorkflowWorkflowIDParams object
// with the ability to set a context for a request.
func NewDeleteHourlyPaidLeaveWorkflowWorkflowIDParamsWithContext(ctx context.Context) *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	return &DeleteHourlyPaidLeaveWorkflowWorkflowIDParams{
		Context: ctx,
	}
}

// NewDeleteHourlyPaidLeaveWorkflowWorkflowIDParamsWithHTTPClient creates a new DeleteHourlyPaidLeaveWorkflowWorkflowIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteHourlyPaidLeaveWorkflowWorkflowIDParamsWithHTTPClient(client *http.Client) *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	return &DeleteHourlyPaidLeaveWorkflowWorkflowIDParams{
		HTTPClient: client,
	}
}

/* DeleteHourlyPaidLeaveWorkflowWorkflowIDParams contains all the parameters to send to the API endpoint
   for the delete hourly paid leave workflow workflow ID operation.

   Typically these are written to a http.Request.
*/
type DeleteHourlyPaidLeaveWorkflowWorkflowIDParams struct {

	/* Note.

	   差戻しコメント
	*/
	Note *string

	/* WorkflowID.

	   申請ID
	*/
	WorkflowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete hourly paid leave workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) WithDefaults() *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete hourly paid leave workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) WithTimeout(timeout time.Duration) *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) WithContext(ctx context.Context) *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) WithHTTPClient(client *http.Client) *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNote adds the note to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) WithNote(note *string) *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetNote(note)
	return o
}

// SetNote adds the note to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) SetNote(note *string) {
	o.Note = note
}

// WithWorkflowID adds the workflowID to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) WithWorkflowID(workflowID string) *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetWorkflowID(workflowID)
	return o
}

// SetWorkflowID adds the workflowId to the delete hourly paid leave workflow workflow ID params
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) SetWorkflowID(workflowID string) {
	o.WorkflowID = workflowID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteHourlyPaidLeaveWorkflowWorkflowIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Note != nil {

		// form param note
		var frNote string
		if o.Note != nil {
			frNote = *o.Note
		}
		fNote := frNote
		if fNote != "" {
			if err := r.SetFormParam("note", fNote); err != nil {
				return err
			}
		}
	}

	// path param workflowID
	if err := r.SetPathParam("workflowID", o.WorkflowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
