// Code generated by go-swagger; DO NOT EDIT.

package hourly_paid_leave_workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kekecone/go-kincone/kinkone"
)

// GetHourlyPaidLeaveWorkflowsReader is a Reader for the GetHourlyPaidLeaveWorkflows structure.
type GetHourlyPaidLeaveWorkflowsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHourlyPaidLeaveWorkflowsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHourlyPaidLeaveWorkflowsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetHourlyPaidLeaveWorkflowsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetHourlyPaidLeaveWorkflowsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetHourlyPaidLeaveWorkflowsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetHourlyPaidLeaveWorkflowsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHourlyPaidLeaveWorkflowsOK creates a GetHourlyPaidLeaveWorkflowsOK with default headers values
func NewGetHourlyPaidLeaveWorkflowsOK() *GetHourlyPaidLeaveWorkflowsOK {
	return &GetHourlyPaidLeaveWorkflowsOK{}
}

/* GetHourlyPaidLeaveWorkflowsOK describes a response with status code 200, with default header values.

正常時
*/
type GetHourlyPaidLeaveWorkflowsOK struct {
	Payload *GetHourlyPaidLeaveWorkflowsOKBody
}

func (o *GetHourlyPaidLeaveWorkflowsOK) Error() string {
	return fmt.Sprintf("[GET /hourly_paid_leave/workflows][%d] getHourlyPaidLeaveWorkflowsOK  %+v", 200, o.Payload)
}
func (o *GetHourlyPaidLeaveWorkflowsOK) GetPayload() *GetHourlyPaidLeaveWorkflowsOKBody {
	return o.Payload
}

func (o *GetHourlyPaidLeaveWorkflowsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetHourlyPaidLeaveWorkflowsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHourlyPaidLeaveWorkflowsUnauthorized creates a GetHourlyPaidLeaveWorkflowsUnauthorized with default headers values
func NewGetHourlyPaidLeaveWorkflowsUnauthorized() *GetHourlyPaidLeaveWorkflowsUnauthorized {
	return &GetHourlyPaidLeaveWorkflowsUnauthorized{}
}

/* GetHourlyPaidLeaveWorkflowsUnauthorized describes a response with status code 401, with default header values.

APIトークンの値を確認して下さい。
*/
type GetHourlyPaidLeaveWorkflowsUnauthorized struct {
	Payload *kinkone.ErrorModel
}

func (o *GetHourlyPaidLeaveWorkflowsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /hourly_paid_leave/workflows][%d] getHourlyPaidLeaveWorkflowsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetHourlyPaidLeaveWorkflowsUnauthorized) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *GetHourlyPaidLeaveWorkflowsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHourlyPaidLeaveWorkflowsForbidden creates a GetHourlyPaidLeaveWorkflowsForbidden with default headers values
func NewGetHourlyPaidLeaveWorkflowsForbidden() *GetHourlyPaidLeaveWorkflowsForbidden {
	return &GetHourlyPaidLeaveWorkflowsForbidden{}
}

/* GetHourlyPaidLeaveWorkflowsForbidden describes a response with status code 403, with default header values.

APIにアクセスする権限がありません。
*/
type GetHourlyPaidLeaveWorkflowsForbidden struct {
	Payload *kinkone.ErrorModel
}

func (o *GetHourlyPaidLeaveWorkflowsForbidden) Error() string {
	return fmt.Sprintf("[GET /hourly_paid_leave/workflows][%d] getHourlyPaidLeaveWorkflowsForbidden  %+v", 403, o.Payload)
}
func (o *GetHourlyPaidLeaveWorkflowsForbidden) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *GetHourlyPaidLeaveWorkflowsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHourlyPaidLeaveWorkflowsUnprocessableEntity creates a GetHourlyPaidLeaveWorkflowsUnprocessableEntity with default headers values
func NewGetHourlyPaidLeaveWorkflowsUnprocessableEntity() *GetHourlyPaidLeaveWorkflowsUnprocessableEntity {
	return &GetHourlyPaidLeaveWorkflowsUnprocessableEntity{}
}

/* GetHourlyPaidLeaveWorkflowsUnprocessableEntity describes a response with status code 422, with default header values.

パラメータの値を確認して下さい。
*/
type GetHourlyPaidLeaveWorkflowsUnprocessableEntity struct {
	Payload *kinkone.ErrorModel
}

func (o *GetHourlyPaidLeaveWorkflowsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /hourly_paid_leave/workflows][%d] getHourlyPaidLeaveWorkflowsUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *GetHourlyPaidLeaveWorkflowsUnprocessableEntity) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *GetHourlyPaidLeaveWorkflowsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHourlyPaidLeaveWorkflowsInternalServerError creates a GetHourlyPaidLeaveWorkflowsInternalServerError with default headers values
func NewGetHourlyPaidLeaveWorkflowsInternalServerError() *GetHourlyPaidLeaveWorkflowsInternalServerError {
	return &GetHourlyPaidLeaveWorkflowsInternalServerError{}
}

/* GetHourlyPaidLeaveWorkflowsInternalServerError describes a response with status code 500, with default header values.

APIサーバーの内部的なエラーです。
*/
type GetHourlyPaidLeaveWorkflowsInternalServerError struct {
	Payload *kinkone.ErrorModel
}

func (o *GetHourlyPaidLeaveWorkflowsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /hourly_paid_leave/workflows][%d] getHourlyPaidLeaveWorkflowsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetHourlyPaidLeaveWorkflowsInternalServerError) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *GetHourlyPaidLeaveWorkflowsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetHourlyPaidLeaveWorkflowsOKBody get hourly paid leave workflows o k body
swagger:model GetHourlyPaidLeaveWorkflowsOKBody
*/
type GetHourlyPaidLeaveWorkflowsOKBody struct {

	// response
	Response *GetHourlyPaidLeaveWorkflowsOKBodyResponse `json:"response,omitempty"`

	// 結果コード
	ResultCode string `json:"result_code,omitempty"`

	// 結果ステータス
	Status bool `json:"status,omitempty"`
}

// Validate validates this get hourly paid leave workflows o k body
func (o *GetHourlyPaidLeaveWorkflowsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResponse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetHourlyPaidLeaveWorkflowsOKBody) validateResponse(formats strfmt.Registry) error {
	if swag.IsZero(o.Response) { // not required
		return nil
	}

	if o.Response != nil {
		if err := o.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHourlyPaidLeaveWorkflowsOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get hourly paid leave workflows o k body based on the context it is used
func (o *GetHourlyPaidLeaveWorkflowsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetHourlyPaidLeaveWorkflowsOKBody) contextValidateResponse(ctx context.Context, formats strfmt.Registry) error {

	if o.Response != nil {
		if err := o.Response.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHourlyPaidLeaveWorkflowsOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetHourlyPaidLeaveWorkflowsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHourlyPaidLeaveWorkflowsOKBody) UnmarshalBinary(b []byte) error {
	var res GetHourlyPaidLeaveWorkflowsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetHourlyPaidLeaveWorkflowsOKBodyResponse APIレスポンス
swagger:model GetHourlyPaidLeaveWorkflowsOKBodyResponse
*/
type GetHourlyPaidLeaveWorkflowsOKBodyResponse struct {

	// workflows
	Workflows []*kinkone.HourlyPaidLeaveWorkflowModel `json:"workflows"`
}

// Validate validates this get hourly paid leave workflows o k body response
func (o *GetHourlyPaidLeaveWorkflowsOKBodyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateWorkflows(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetHourlyPaidLeaveWorkflowsOKBodyResponse) validateWorkflows(formats strfmt.Registry) error {
	if swag.IsZero(o.Workflows) { // not required
		return nil
	}

	for i := 0; i < len(o.Workflows); i++ {
		if swag.IsZero(o.Workflows[i]) { // not required
			continue
		}

		if o.Workflows[i] != nil {
			if err := o.Workflows[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getHourlyPaidLeaveWorkflowsOK" + "." + "response" + "." + "workflows" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get hourly paid leave workflows o k body response based on the context it is used
func (o *GetHourlyPaidLeaveWorkflowsOKBodyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateWorkflows(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetHourlyPaidLeaveWorkflowsOKBodyResponse) contextValidateWorkflows(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Workflows); i++ {

		if o.Workflows[i] != nil {
			if err := o.Workflows[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getHourlyPaidLeaveWorkflowsOK" + "." + "response" + "." + "workflows" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetHourlyPaidLeaveWorkflowsOKBodyResponse) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHourlyPaidLeaveWorkflowsOKBodyResponse) UnmarshalBinary(b []byte) error {
	var res GetHourlyPaidLeaveWorkflowsOKBodyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
