// Code generated by go-swagger; DO NOT EDIT.

package hourly_paid_leave_workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostHourlyPaidLeaveWorkflowWorkflowIDParams creates a new PostHourlyPaidLeaveWorkflowWorkflowIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostHourlyPaidLeaveWorkflowWorkflowIDParams() *PostHourlyPaidLeaveWorkflowWorkflowIDParams {
	return &PostHourlyPaidLeaveWorkflowWorkflowIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostHourlyPaidLeaveWorkflowWorkflowIDParamsWithTimeout creates a new PostHourlyPaidLeaveWorkflowWorkflowIDParams object
// with the ability to set a timeout on a request.
func NewPostHourlyPaidLeaveWorkflowWorkflowIDParamsWithTimeout(timeout time.Duration) *PostHourlyPaidLeaveWorkflowWorkflowIDParams {
	return &PostHourlyPaidLeaveWorkflowWorkflowIDParams{
		timeout: timeout,
	}
}

// NewPostHourlyPaidLeaveWorkflowWorkflowIDParamsWithContext creates a new PostHourlyPaidLeaveWorkflowWorkflowIDParams object
// with the ability to set a context for a request.
func NewPostHourlyPaidLeaveWorkflowWorkflowIDParamsWithContext(ctx context.Context) *PostHourlyPaidLeaveWorkflowWorkflowIDParams {
	return &PostHourlyPaidLeaveWorkflowWorkflowIDParams{
		Context: ctx,
	}
}

// NewPostHourlyPaidLeaveWorkflowWorkflowIDParamsWithHTTPClient creates a new PostHourlyPaidLeaveWorkflowWorkflowIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostHourlyPaidLeaveWorkflowWorkflowIDParamsWithHTTPClient(client *http.Client) *PostHourlyPaidLeaveWorkflowWorkflowIDParams {
	return &PostHourlyPaidLeaveWorkflowWorkflowIDParams{
		HTTPClient: client,
	}
}

/* PostHourlyPaidLeaveWorkflowWorkflowIDParams contains all the parameters to send to the API endpoint
   for the post hourly paid leave workflow workflow ID operation.

   Typically these are written to a http.Request.
*/
type PostHourlyPaidLeaveWorkflowWorkflowIDParams struct {

	/* WorkflowID.

	   申請ID
	*/
	WorkflowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post hourly paid leave workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) WithDefaults() *PostHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post hourly paid leave workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post hourly paid leave workflow workflow ID params
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) WithTimeout(timeout time.Duration) *PostHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post hourly paid leave workflow workflow ID params
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post hourly paid leave workflow workflow ID params
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) WithContext(ctx context.Context) *PostHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post hourly paid leave workflow workflow ID params
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post hourly paid leave workflow workflow ID params
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) WithHTTPClient(client *http.Client) *PostHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post hourly paid leave workflow workflow ID params
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflowID adds the workflowID to the post hourly paid leave workflow workflow ID params
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) WithWorkflowID(workflowID string) *PostHourlyPaidLeaveWorkflowWorkflowIDParams {
	o.SetWorkflowID(workflowID)
	return o
}

// SetWorkflowID adds the workflowId to the post hourly paid leave workflow workflow ID params
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) SetWorkflowID(workflowID string) {
	o.WorkflowID = workflowID
}

// WriteToRequest writes these params to a swagger request
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workflowID
	if err := r.SetPathParam("workflowID", o.WorkflowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
