// Code generated by go-swagger; DO NOT EDIT.

package hourly_paid_leave_workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kekecone/go-kincone/kinkone/model"
)

// PostHourlyPaidLeaveWorkflowWorkflowIDReader is a Reader for the PostHourlyPaidLeaveWorkflowWorkflowID structure.
type PostHourlyPaidLeaveWorkflowWorkflowIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostHourlyPaidLeaveWorkflowWorkflowIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostHourlyPaidLeaveWorkflowWorkflowIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostHourlyPaidLeaveWorkflowWorkflowIDOK creates a PostHourlyPaidLeaveWorkflowWorkflowIDOK with default headers values
func NewPostHourlyPaidLeaveWorkflowWorkflowIDOK() *PostHourlyPaidLeaveWorkflowWorkflowIDOK {
	return &PostHourlyPaidLeaveWorkflowWorkflowIDOK{}
}

/* PostHourlyPaidLeaveWorkflowWorkflowIDOK describes a response with status code 200, with default header values.

正常時
*/
type PostHourlyPaidLeaveWorkflowWorkflowIDOK struct {
	Payload *PostHourlyPaidLeaveWorkflowWorkflowIDOKBody
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOK) Error() string {
	return fmt.Sprintf("[POST /hourly_paid_leave/workflow/{workflowID}][%d] postHourlyPaidLeaveWorkflowWorkflowIdOK  %+v", 200, o.Payload)
}
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOK) GetPayload() *PostHourlyPaidLeaveWorkflowWorkflowIDOKBody {
	return o.Payload
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostHourlyPaidLeaveWorkflowWorkflowIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized creates a PostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized with default headers values
func NewPostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized() *PostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized {
	return &PostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized{}
}

/* PostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized describes a response with status code 401, with default header values.

APIトークンの値を確認して下さい。
*/
type PostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized struct {
	Payload *model.ErrorModel
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized) Error() string {
	return fmt.Sprintf("[POST /hourly_paid_leave/workflow/{workflowID}][%d] postHourlyPaidLeaveWorkflowWorkflowIdUnauthorized  %+v", 401, o.Payload)
}
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostHourlyPaidLeaveWorkflowWorkflowIDForbidden creates a PostHourlyPaidLeaveWorkflowWorkflowIDForbidden with default headers values
func NewPostHourlyPaidLeaveWorkflowWorkflowIDForbidden() *PostHourlyPaidLeaveWorkflowWorkflowIDForbidden {
	return &PostHourlyPaidLeaveWorkflowWorkflowIDForbidden{}
}

/* PostHourlyPaidLeaveWorkflowWorkflowIDForbidden describes a response with status code 403, with default header values.

APIにアクセスする権限がありません。
*/
type PostHourlyPaidLeaveWorkflowWorkflowIDForbidden struct {
	Payload *model.ErrorModel
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDForbidden) Error() string {
	return fmt.Sprintf("[POST /hourly_paid_leave/workflow/{workflowID}][%d] postHourlyPaidLeaveWorkflowWorkflowIdForbidden  %+v", 403, o.Payload)
}
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDForbidden) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity creates a PostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity with default headers values
func NewPostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity() *PostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity {
	return &PostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity{}
}

/* PostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity describes a response with status code 422, with default header values.

パラメータの値を確認して下さい。
*/
type PostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity struct {
	Payload *model.ErrorModel
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /hourly_paid_leave/workflow/{workflowID}][%d] postHourlyPaidLeaveWorkflowWorkflowIdUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError creates a PostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError with default headers values
func NewPostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError() *PostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError {
	return &PostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError{}
}

/* PostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError describes a response with status code 500, with default header values.

APIサーバーの内部的なエラーです。
*/
type PostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError struct {
	Payload *model.ErrorModel
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError) Error() string {
	return fmt.Sprintf("[POST /hourly_paid_leave/workflow/{workflowID}][%d] postHourlyPaidLeaveWorkflowWorkflowIdInternalServerError  %+v", 500, o.Payload)
}
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError) GetPayload() *model.ErrorModel {
	return o.Payload
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostHourlyPaidLeaveWorkflowWorkflowIDOKBody post hourly paid leave workflow workflow ID o k body
swagger:model PostHourlyPaidLeaveWorkflowWorkflowIDOKBody
*/
type PostHourlyPaidLeaveWorkflowWorkflowIDOKBody struct {

	// response
	Response *PostHourlyPaidLeaveWorkflowWorkflowIDOKBodyResponse `json:"response,omitempty"`

	// 結果コード
	ResultCode string `json:"result_code,omitempty"`

	// 結果ステータス
	Status bool `json:"status,omitempty"`
}

// Validate validates this post hourly paid leave workflow workflow ID o k body
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResponse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBody) validateResponse(formats strfmt.Registry) error {
	if swag.IsZero(o.Response) { // not required
		return nil
	}

	if o.Response != nil {
		if err := o.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postHourlyPaidLeaveWorkflowWorkflowIdOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post hourly paid leave workflow workflow ID o k body based on the context it is used
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBody) contextValidateResponse(ctx context.Context, formats strfmt.Registry) error {

	if o.Response != nil {
		if err := o.Response.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postHourlyPaidLeaveWorkflowWorkflowIdOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBody) UnmarshalBinary(b []byte) error {
	var res PostHourlyPaidLeaveWorkflowWorkflowIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostHourlyPaidLeaveWorkflowWorkflowIDOKBodyResponse APIレスポンス
swagger:model PostHourlyPaidLeaveWorkflowWorkflowIDOKBodyResponse
*/
type PostHourlyPaidLeaveWorkflowWorkflowIDOKBodyResponse struct {

	// 処理結果
	Result bool `json:"result,omitempty"`
}

// Validate validates this post hourly paid leave workflow workflow ID o k body response
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBodyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post hourly paid leave workflow workflow ID o k body response based on context it is used
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBodyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBodyResponse) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostHourlyPaidLeaveWorkflowWorkflowIDOKBodyResponse) UnmarshalBinary(b []byte) error {
	var res PostHourlyPaidLeaveWorkflowWorkflowIDOKBodyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
