// Code generated by go-swagger; DO NOT EDIT.

package attendance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new attendance API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for attendance API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PostAttendance(params *PostAttendanceParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAttendanceOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  PostAttendance 勤怠登録s 更新

  指定した従業員と出勤日に該当する勤怠明細を登録・更新します。<br>就業形態の「休憩の付与方法」が "一定時間以上勤務した場合に付与する" の場合は休憩時間が自動的に計算されます。
*/
func (a *Client) PostAttendance(params *PostAttendanceParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAttendanceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostAttendanceParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAttendance",
		Method:             "POST",
		PathPattern:        "/attendance",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostAttendanceReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostAttendanceOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAttendance: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
