// Code generated by go-swagger; DO NOT EDIT.

package attendance_workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kekecone/go-kincone/kinkone"
)

// DeleteAttendanceWorkflowWorkflowIDReader is a Reader for the DeleteAttendanceWorkflowWorkflowID structure.
type DeleteAttendanceWorkflowWorkflowIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAttendanceWorkflowWorkflowIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAttendanceWorkflowWorkflowIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteAttendanceWorkflowWorkflowIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAttendanceWorkflowWorkflowIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteAttendanceWorkflowWorkflowIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAttendanceWorkflowWorkflowIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAttendanceWorkflowWorkflowIDOK creates a DeleteAttendanceWorkflowWorkflowIDOK with default headers values
func NewDeleteAttendanceWorkflowWorkflowIDOK() *DeleteAttendanceWorkflowWorkflowIDOK {
	return &DeleteAttendanceWorkflowWorkflowIDOK{}
}

/* DeleteAttendanceWorkflowWorkflowIDOK describes a response with status code 200, with default header values.

正常時
*/
type DeleteAttendanceWorkflowWorkflowIDOK struct {
	Payload *DeleteAttendanceWorkflowWorkflowIDOKBody
}

func (o *DeleteAttendanceWorkflowWorkflowIDOK) Error() string {
	return fmt.Sprintf("[DELETE /attendance/workflow/{workflowID}][%d] deleteAttendanceWorkflowWorkflowIdOK  %+v", 200, o.Payload)
}
func (o *DeleteAttendanceWorkflowWorkflowIDOK) GetPayload() *DeleteAttendanceWorkflowWorkflowIDOKBody {
	return o.Payload
}

func (o *DeleteAttendanceWorkflowWorkflowIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteAttendanceWorkflowWorkflowIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceWorkflowWorkflowIDUnauthorized creates a DeleteAttendanceWorkflowWorkflowIDUnauthorized with default headers values
func NewDeleteAttendanceWorkflowWorkflowIDUnauthorized() *DeleteAttendanceWorkflowWorkflowIDUnauthorized {
	return &DeleteAttendanceWorkflowWorkflowIDUnauthorized{}
}

/* DeleteAttendanceWorkflowWorkflowIDUnauthorized describes a response with status code 401, with default header values.

APIトークンの値を確認して下さい。
*/
type DeleteAttendanceWorkflowWorkflowIDUnauthorized struct {
	Payload *kinkone.ErrorModel
}

func (o *DeleteAttendanceWorkflowWorkflowIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /attendance/workflow/{workflowID}][%d] deleteAttendanceWorkflowWorkflowIdUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteAttendanceWorkflowWorkflowIDUnauthorized) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceWorkflowWorkflowIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceWorkflowWorkflowIDForbidden creates a DeleteAttendanceWorkflowWorkflowIDForbidden with default headers values
func NewDeleteAttendanceWorkflowWorkflowIDForbidden() *DeleteAttendanceWorkflowWorkflowIDForbidden {
	return &DeleteAttendanceWorkflowWorkflowIDForbidden{}
}

/* DeleteAttendanceWorkflowWorkflowIDForbidden describes a response with status code 403, with default header values.

APIにアクセスする権限がありません。
*/
type DeleteAttendanceWorkflowWorkflowIDForbidden struct {
	Payload *kinkone.ErrorModel
}

func (o *DeleteAttendanceWorkflowWorkflowIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /attendance/workflow/{workflowID}][%d] deleteAttendanceWorkflowWorkflowIdForbidden  %+v", 403, o.Payload)
}
func (o *DeleteAttendanceWorkflowWorkflowIDForbidden) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceWorkflowWorkflowIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceWorkflowWorkflowIDUnprocessableEntity creates a DeleteAttendanceWorkflowWorkflowIDUnprocessableEntity with default headers values
func NewDeleteAttendanceWorkflowWorkflowIDUnprocessableEntity() *DeleteAttendanceWorkflowWorkflowIDUnprocessableEntity {
	return &DeleteAttendanceWorkflowWorkflowIDUnprocessableEntity{}
}

/* DeleteAttendanceWorkflowWorkflowIDUnprocessableEntity describes a response with status code 422, with default header values.

パラメータの値を確認して下さい。
*/
type DeleteAttendanceWorkflowWorkflowIDUnprocessableEntity struct {
	Payload *kinkone.ErrorModel
}

func (o *DeleteAttendanceWorkflowWorkflowIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /attendance/workflow/{workflowID}][%d] deleteAttendanceWorkflowWorkflowIdUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *DeleteAttendanceWorkflowWorkflowIDUnprocessableEntity) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceWorkflowWorkflowIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAttendanceWorkflowWorkflowIDInternalServerError creates a DeleteAttendanceWorkflowWorkflowIDInternalServerError with default headers values
func NewDeleteAttendanceWorkflowWorkflowIDInternalServerError() *DeleteAttendanceWorkflowWorkflowIDInternalServerError {
	return &DeleteAttendanceWorkflowWorkflowIDInternalServerError{}
}

/* DeleteAttendanceWorkflowWorkflowIDInternalServerError describes a response with status code 500, with default header values.

APIサーバーの内部的なエラーです。
*/
type DeleteAttendanceWorkflowWorkflowIDInternalServerError struct {
	Payload *kinkone.ErrorModel
}

func (o *DeleteAttendanceWorkflowWorkflowIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /attendance/workflow/{workflowID}][%d] deleteAttendanceWorkflowWorkflowIdInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteAttendanceWorkflowWorkflowIDInternalServerError) GetPayload() *kinkone.ErrorModel {
	return o.Payload
}

func (o *DeleteAttendanceWorkflowWorkflowIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kinkone.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteAttendanceWorkflowWorkflowIDOKBody delete attendance workflow workflow ID o k body
swagger:model DeleteAttendanceWorkflowWorkflowIDOKBody
*/
type DeleteAttendanceWorkflowWorkflowIDOKBody struct {

	// response
	Response *DeleteAttendanceWorkflowWorkflowIDOKBodyResponse `json:"response,omitempty"`

	// 結果コード
	ResultCode string `json:"result_code,omitempty"`

	// 結果ステータス
	Status bool `json:"status,omitempty"`
}

// Validate validates this delete attendance workflow workflow ID o k body
func (o *DeleteAttendanceWorkflowWorkflowIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResponse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceWorkflowWorkflowIDOKBody) validateResponse(formats strfmt.Registry) error {
	if swag.IsZero(o.Response) { // not required
		return nil
	}

	if o.Response != nil {
		if err := o.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceWorkflowWorkflowIdOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete attendance workflow workflow ID o k body based on the context it is used
func (o *DeleteAttendanceWorkflowWorkflowIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAttendanceWorkflowWorkflowIDOKBody) contextValidateResponse(ctx context.Context, formats strfmt.Registry) error {

	if o.Response != nil {
		if err := o.Response.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteAttendanceWorkflowWorkflowIdOK" + "." + "response")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteAttendanceWorkflowWorkflowIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteAttendanceWorkflowWorkflowIDOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteAttendanceWorkflowWorkflowIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteAttendanceWorkflowWorkflowIDOKBodyResponse APIレスポンス
swagger:model DeleteAttendanceWorkflowWorkflowIDOKBodyResponse
*/
type DeleteAttendanceWorkflowWorkflowIDOKBodyResponse struct {

	// 処理結果
	Result bool `json:"result,omitempty"`
}

// Validate validates this delete attendance workflow workflow ID o k body response
func (o *DeleteAttendanceWorkflowWorkflowIDOKBodyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete attendance workflow workflow ID o k body response based on context it is used
func (o *DeleteAttendanceWorkflowWorkflowIDOKBodyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteAttendanceWorkflowWorkflowIDOKBodyResponse) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteAttendanceWorkflowWorkflowIDOKBodyResponse) UnmarshalBinary(b []byte) error {
	var res DeleteAttendanceWorkflowWorkflowIDOKBodyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
