// Code generated by go-swagger; DO NOT EDIT.

package attendance_workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAttendanceWorkflowWorkflowIDParams creates a new PostAttendanceWorkflowWorkflowIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAttendanceWorkflowWorkflowIDParams() *PostAttendanceWorkflowWorkflowIDParams {
	return &PostAttendanceWorkflowWorkflowIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAttendanceWorkflowWorkflowIDParamsWithTimeout creates a new PostAttendanceWorkflowWorkflowIDParams object
// with the ability to set a timeout on a request.
func NewPostAttendanceWorkflowWorkflowIDParamsWithTimeout(timeout time.Duration) *PostAttendanceWorkflowWorkflowIDParams {
	return &PostAttendanceWorkflowWorkflowIDParams{
		timeout: timeout,
	}
}

// NewPostAttendanceWorkflowWorkflowIDParamsWithContext creates a new PostAttendanceWorkflowWorkflowIDParams object
// with the ability to set a context for a request.
func NewPostAttendanceWorkflowWorkflowIDParamsWithContext(ctx context.Context) *PostAttendanceWorkflowWorkflowIDParams {
	return &PostAttendanceWorkflowWorkflowIDParams{
		Context: ctx,
	}
}

// NewPostAttendanceWorkflowWorkflowIDParamsWithHTTPClient creates a new PostAttendanceWorkflowWorkflowIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAttendanceWorkflowWorkflowIDParamsWithHTTPClient(client *http.Client) *PostAttendanceWorkflowWorkflowIDParams {
	return &PostAttendanceWorkflowWorkflowIDParams{
		HTTPClient: client,
	}
}

/* PostAttendanceWorkflowWorkflowIDParams contains all the parameters to send to the API endpoint
   for the post attendance workflow workflow ID operation.

   Typically these are written to a http.Request.
*/
type PostAttendanceWorkflowWorkflowIDParams struct {

	/* WorkflowID.

	   申請ID
	*/
	WorkflowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post attendance workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAttendanceWorkflowWorkflowIDParams) WithDefaults() *PostAttendanceWorkflowWorkflowIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post attendance workflow workflow ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAttendanceWorkflowWorkflowIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post attendance workflow workflow ID params
func (o *PostAttendanceWorkflowWorkflowIDParams) WithTimeout(timeout time.Duration) *PostAttendanceWorkflowWorkflowIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post attendance workflow workflow ID params
func (o *PostAttendanceWorkflowWorkflowIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post attendance workflow workflow ID params
func (o *PostAttendanceWorkflowWorkflowIDParams) WithContext(ctx context.Context) *PostAttendanceWorkflowWorkflowIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post attendance workflow workflow ID params
func (o *PostAttendanceWorkflowWorkflowIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post attendance workflow workflow ID params
func (o *PostAttendanceWorkflowWorkflowIDParams) WithHTTPClient(client *http.Client) *PostAttendanceWorkflowWorkflowIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post attendance workflow workflow ID params
func (o *PostAttendanceWorkflowWorkflowIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflowID adds the workflowID to the post attendance workflow workflow ID params
func (o *PostAttendanceWorkflowWorkflowIDParams) WithWorkflowID(workflowID string) *PostAttendanceWorkflowWorkflowIDParams {
	o.SetWorkflowID(workflowID)
	return o
}

// SetWorkflowID adds the workflowId to the post attendance workflow workflow ID params
func (o *PostAttendanceWorkflowWorkflowIDParams) SetWorkflowID(workflowID string) {
	o.WorkflowID = workflowID
}

// WriteToRequest writes these params to a swagger request
func (o *PostAttendanceWorkflowWorkflowIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workflowID
	if err := r.SetPathParam("workflowID", o.WorkflowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
